# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Recieve.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(730, 601)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(120, 140, 491, 261))
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 110, 111, 16))
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(100, 420, 551, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(100, 510, 551, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 460, 407, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Recieve_file = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Recieve_file.setObjectName("pushButton_Recieve_file")
        self.horizontalLayout.addWidget(self.pushButton_Recieve_file)
        self.pushButton_decrypted_AES_key = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_decrypted_AES_key.setObjectName("pushButton_decrypted_AES_key")
        self.horizontalLayout.addWidget(self.pushButton_decrypted_AES_key)
        self.pushButton_decrypted_ciphertext = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_decrypted_ciphertext.setObjectName("pushButton_decrypted_ciphertext")
        self.horizontalLayout.addWidget(self.pushButton_decrypted_ciphertext)
        self.pushButton_verify_sign = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_verify_sign.setObjectName("pushButton_verify_sign")
        self.horizontalLayout.addWidget(self.pushButton_verify_sign)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 60, 195, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Send_public_key = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_Send_public_key.setObjectName("pushButton_Send_public_key")
        self.horizontalLayout_2.addWidget(self.pushButton_Send_public_key)
        self.pushButton_Recievefile_public_key = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_Recievefile_public_key.setObjectName("pushButton_Recievefile_public_key")
        self.horizontalLayout_2.addWidget(self.pushButton_Recievefile_public_key)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Bob"))
        self.label_4.setText(_translate("Form", "消息提示框："))
        self.pushButton_Recieve_file.setText(_translate("Form", "接收文件"))
        self.pushButton_decrypted_AES_key.setText(_translate("Form", "解密对称密钥"))
        self.pushButton_decrypted_ciphertext.setText(_translate("Form", "解密密文"))
        self.pushButton_verify_sign.setText(_translate("Form", "验证数字签名"))
        self.pushButton_Send_public_key.setText(_translate("Form", "发送公钥"))
        self.pushButton_Recievefile_public_key.setText(_translate("Form", "接收公钥"))
